# Generated by Django 5.2.8 on 2026-01-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveyapp', '0002_surveyresult_content_type_surveyresult_object_id'),
        ('trainees', '0002_trainee_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='trainee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trainees.trainee'),
            preserve_default=False,
        ),
    ]
