# Generated by Django 5.2.8 on 2026-02-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('surveyapp', '0003_surveyresult_trainee'),
        ('trainees', '0004_alter_trainee_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainees.trainee')),
            ],
        ),
    ]
