# Generated by Django 5.2.8 on 2026-01-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0002_trainee_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='survey_round_1_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainee',
            name='survey_round_2_sent',
            field=models.BooleanField(default=False),
        ),
    ]
