# Generated by Django 5.2.8 on 2026-01-13 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0003_trainee_survey_round_1_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
